import { TextStyle } from 'react-native';

export enum CCFontFamilies {
  Black = 'Inter-Black',
  Bold = 'Inter-Bold',
  BoldItalic = 'Inter-BoldItalic',
  ExtraBold = 'Inter-ExtraBold',
  ExtraBoldItalic = 'Inter-ExtraBoldItalic',
  ExtraLight = 'Inter-ExtraLight-BETA',
  ExtraLightItalic = 'Inter-ExtraLightItalic-BETA',
  Italic = 'Inter-Italic',
  Light = 'Inter-Light-BETA',
  LightItalic = 'Inter-LightItalic-BETA',
  Medium = 'Inter-Medium',
  MediumItalic = 'Inter-MediumItalic',
  Regular = 'Inter-Regular',
  SemiBold = 'Inter-SemiBold',
  SemiBoldItalic = 'Inter-SemiBoldItalic',
  Thin = 'Inter-Thin-BETA',
  ThinItalic = 'Inter-ThinItalic-BETA',
}

export const typography = {
  displayLarge:       { fontFamily: CCFontFamilies.Bold,           fontSize: 40, lineHeight: 48 } as TextStyle,
  displayMedium:      { fontFamily: CCFontFamilies.Bold,           fontSize: 32, lineHeight: 40 } as TextStyle,
  h1:                 { fontFamily: CCFontFamilies.Bold,           fontSize: 28, lineHeight: 36 } as TextStyle,
  h2:                 { fontFamily: CCFontFamilies.SemiBold,       fontSize: 24, lineHeight: 32 } as TextStyle,
  h3:                 { fontFamily: CCFontFamilies.SemiBold,       fontSize: 20, lineHeight: 28 } as TextStyle,
  title:              { fontFamily: CCFontFamilies.SemiBold,       fontSize: 18, lineHeight: 26 } as TextStyle,
  bodyLarge:          { fontFamily: CCFontFamilies.Regular,        fontSize: 16, lineHeight: 24 } as TextStyle,
  body:               { fontFamily: CCFontFamilies.Regular,        fontSize: 14, lineHeight: 20 } as TextStyle,
  bodySmall:          { fontFamily: CCFontFamilies.Regular,        fontSize: 12, lineHeight: 18 } as TextStyle,
  labelLarge:         { fontFamily: CCFontFamilies.Medium,         fontSize: 14, lineHeight: 20 } as TextStyle,
  label:              { fontFamily: CCFontFamilies.Medium,         fontSize: 12, lineHeight: 16 } as TextStyle,
  caption:            { fontFamily: CCFontFamilies.Regular,        fontSize: 11, lineHeight: 16 } as TextStyle,
  tiny:               { fontFamily: CCFontFamilies.Regular,        fontSize: 10, lineHeight: 14 } as TextStyle,
  bodyReg:            { fontFamily: CCFontFamilies.Regular,        fontSize: 14, lineHeight: 20 } as TextStyle,
  bodyRegItalic:      { fontFamily: CCFontFamilies.Italic,         fontSize: 14, lineHeight: 20 } as TextStyle,
  bodySemiBold:       { fontFamily: CCFontFamilies.SemiBold,       fontSize: 14, lineHeight: 20 } as TextStyle,
  bodySemiBoldItalic: { fontFamily: CCFontFamilies.SemiBoldItalic, fontSize: 14, lineHeight: 20 } as TextStyle,
  h3Bold:             { fontFamily: CCFontFamilies.Bold,           fontSize: 20, lineHeight: 28 } as TextStyle,
  buttonMedium:       { fontFamily: CCFontFamilies.SemiBold,       fontSize: 14, lineHeight: 20 } as TextStyle,
} as const;
