name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'none'
        type: choice
        options:
          - none
          - patch
          - minor
          - major

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@hvalec427'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bump version
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          yarn version --${{ (github.event_name == 'workflow_dispatch' && inputs.version_bump != 'none') && inputs.version_bump || 'minor' }} --message "chore: bump version to %s [skip ci]"
          git pull --rebase
          git push
          git push --tags

      - name: Build
        run: yarn build

      - name: Publish to GitHub Packages
        run: yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
